name: e_commerce_flutter
description: E-Commerce App built in flutter using GetX


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  get:
  firebase_auth:
  firebase_core:
  smooth_page_indicator:
  flutter_rating_bar:
  font_awesome_flutter:
  webview_flutter:
  animations:
  community_material_icon:
  page_transition:


dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/
